apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: exam
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcluster:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&allowEmptyPassword=yes&createDatabaseIfNotExist=true&autoReconnect=true
  SPRING_DATASOURCE_USERNAME: root

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: exam
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: unkindled1/spring-service:v5
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: SPRING_DATASOURCE_USERNAME
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 15
        startupProbe:
          exec:
            command:
            - touch
            - /tmp/healthy  # Créer le fichier /tmp/healthy lors de la sonde de démarrage
          failureThreshold: 30
