# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: exam
  name: exam-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-role-binding
  namespace: exam
subjects:
- kind: User
  name: "amine"  # Replace with your Kubernetes username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: exam-role
  apiGroup: rbac.authorization.k8s.io
